=== department-of-veterans-affairs/content-build/src/applications/registry-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
            "appName": {
                "type": "string"
            },
            "entryName": {
                "type": "string"
            },
            "entryFile": {
                "type": "string"
            },
            "productId": {
                "type": "string"
            },
            "rootUrl": {
                "type": "string"
            },
            "useLocalStylesAndComponents": {
                "type": "boolean"
            },
            "template": {
                "type": "object",
                "properties": {
                    "breadcrumbs_override": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "additionalProperties": false,
                            "properties": {
                                "name": {
                                    "type": "string"
                                },
                                "path": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "collection": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    },
                    "display_title": {
                        "type": "string"
                    },
                    "heading": {
                        "type": "string"
                    },
                    "hideFromSidebar": {
                        "type": "boolean"
                    },
                    "includeBreadcrumbs": {
                        "type": "boolean"
                    },
                    "includeFeedbackButton": {
                        "type": "boolean"
                    },
                    "keywords": {
                        "type": "string"
                    },
                    "layout": {
                        "type": "string"
                    },
                    "loadingMessage": {
                        "type": "string"
                    },
                    "localhost": {
                        "type": "boolean"
                    },
                    "minimalFooter": {
                        "oneOf": [
                            {
                                "default": false,
                                "type": "boolean"
                            },
                            {
                                "type": "object",
                                "additionalProperties": false,
                                "properties": {
                                    "enabled": {
                                        "default": true,
                                        "type": "boolean"
                                    },
                                    "excludePaths": {
                                        "default": ["/introduction", "/confirmation"],
                                        "type": "array",
                                        "items": {
                                            "type": "string",
                                            "pattern": "^/.*"
                                        }
                                    }
                                }
                            }
                        ]
                    },
                    "minimalHeader": {
                        "oneOf": [
                            {
                                "default": false,
                                "type": "boolean"
                            },
                            {
                                "type": "object",
                                "additionalProperties": false,
                                "properties": {
                                    "enabled": {
                                        "default": true,
                                        "type": "boolean"
                                    },
                                    "enableHeadings": {
                                        "description": "Enables use of heading tags in the minimal header instead of <div> tags",
                                        "default": false,
                                        "type": "boolean"
                                    },
                                    "excludePaths": {
                                        "default": ["/introduction", "/confirmation"],
                                        "type": "array",
                                        "items": {
                                            "type": "string",
                                            "pattern": "^/.*"
                                        }
                                    },
                                    "subtitle": {
                                        "type": "string"
                                    },
                                    "title": {
                                        "type": "string"
                                    }
                                }
                            }
                        ]
                    },
                    "noHeader": {
                        "type": "boolean"
                    },
                    "noMegamenu": {
                        "type": "boolean"
                    },
                    "noNavOrLogin": {
                        "type": "boolean"
                    },
                    "order": {
                        "type": "number"
                    },
                    "private": {
                        "type": "boolean"
                    },
                    "spoke": {
                        "type": "string"
                    },
                    "title": {
                        "type": "string"
                    },
                    "vagovdev": {
                        "type": "boolean"
                    },
                    "vagovprod": {
                        "type": "boolean"
                    },
                    "vagovstaging": {
                        "type": "boolean"
                    }
                }
            }
        }
    }
}

=== department-of-veterans-affairs/content-build/src/applications/registry.json
[
  {
    "appName": "COVID-19 screener",
    "entryName": "covid19screen",
    "rootUrl": "/covid19screen",
    "template": {
      "title": "COVID-19 screening tool",
      "layout": "page-react.html",
      "private": true,
      "vagovprod": true
    }
  },
  {
    "appName": "Verify identity",
    "entryName": "verify",
    "rootUrl": "/verify",
    "template": {
      "title": "Verify",
      "layout": "page-react.html"
    }
  },
  {
    "appName": "21-527EZ pension benefits form",
    "entryName": "pensions",
    "rootUrl": "/pension/apply-for-veteran-pension-form-21p-527ez",
    "template": {
      "title": "Apply For Veterans Pension Benefits",
      "heading": "Apply for Veterans pension benefits",
      "display_title": "Apply now",
      "description": "Submit your VA pension application (VA Form 21P-527EZ) online now. Get step-by-step instructions, and consider signing in to save your in-progress application if you need to come back later to finish filling it out.",
      "layout": "page-react.html",
      "spoke": "Get benefits",
      "collection": "pension",
      "order": 3,
      "includeBreadcrumbs": true,
      "breadcrumbs_override": [
        {
          "path": "pension/",
          "name": "Pension benefits"
        },
        {
          "path": "pension/apply-for-veteran-pension-form-21p-527ez",
          "name": "Apply for Veterans Pension benefits"
        }
      ]
    }
  },
  {
    "appName": "Appointments",
    "entryName": "vaos",
    "rootUrl": "/my-health/appointments",
    "template": {
      "vagovprod": true,
      "layout": "page-react.html",
      "private": true
    }
  },
  {
    "appName": "Rated Disabilities",
    "entryName": "rated-disabilities",
    "rootUrl": "/disability/view-disability-rating/rating",
    "template": {
      "layout": "page-react.html",
      "vagovprod": true,
      "includeBreadcrumbs": true,
      "breadcrumbs_override": [
        {
          "path": "disability",
          "name": "Disability benefits"
        },
        {
          "path": "disability/view-disability-rating",
          "name": "View your VA disability rating"
        },
        {
          "path": "disability/view-disability-rating/rating",
          "name": "Your VA disability rating"
        }
      ]
    }
  },
  {
    "appName": "Dashboard",
    "entryName": "dashboard",
    "rootUrl": "/my-va",
    "template": {
      "title": "My VA",
      "layout": "page-react.html"
    }
  },
  {
    "appName": "VA Profile",
    "entryName": "profile",
    "rootUrl": "/profile",
    "template": {
      "title": "Your Profile",
      "layout": "page-react.html"
    }
  },
  {
    "appName": "View Dependents",
    "entryName": "dependents-view-dependents",
    "rootUrl": "/manage-dependents/view",
    "template": {
      "title": "View Dependents",
      "layout": "page-react.html",
      "vagovprod": true,
      "includeBreadcrumbs": true,
      "breadcrumbs_override": [
        {
          "path": "manage-dependents/",
          "name": "Manage dependents for disability, pension, or DIC benefits"
        },
        {
          "path": "manage-dependents/view",
          "name": "Your VA dependents"
        }
      ]
    }
  },
  {
    "appName": "Facility Locator",
    "entryName": "facilities",
    "rootUrl": "/find-locations",
    "template": {
      "title": "Find VA Locations",
      "layout": "page-react.html",
      "description": "Find a VA medical center, clinic, hospital, national cemetery, or VA regional office near you. You can search by city, state, postal code, or service. You'll get wait times and directions.",
      "keywords": "VA location by zip code, VA clinic, VA near me"
    }
  },
  {
    "appName": "10-10CG",
    "entryName": "1010cg-application-caregiver-assistance",
    "rootUrl": "/family-and-caregiver-benefits/health-and-disability/comprehensive-assistance-for-family-caregivers/apply-form-10-10cg",
    "template": {
      "title": "Apply for the Program of Comprehensive Assistance for Family Caregivers",
      "vagovprod": true,
      "vagovstaging": true,
      "vagovdev": true,
      "localhost": true,
      "includeBreadcrumbs": true,
      "breadcrumbs_override": [
        {
          "path": "family-and-caregiver-benefits",
          "name": "Family and caregiver benefits"
        },
        {
          "path": "family-and-caregiver-benefits/health-and-disability",
          "name": "Health and disability benefits for family and caregivers"
        },
        {
          "path": "family-and-caregiver-benefits/health-and-disability/comprehensive-assistance-for-family-caregivers/apply-form-10-10cg",
          "name": "Apply for the Program of Comprehensive Assistance for Family Caregivers"
        }
      ]
    }
  },
  {
    "appName": "Terms of use",
    "entryName": "terms-of-use",
    "rootUrl": "/terms-of-use",
    "template": {
      "title": "VA online services terms of use",
      "layout": "page-react.html",
      "includeBreadcrumbs": false,
      "vagovprod": true
    }
  },
  {
    "appName": "21P-530EZ Burials benefits form",
    "entryName": "burials-ez",
    "rootUrl": "/burials-memorials/veterans-burial-allowance/apply-for-allowance-form-21p-530ez",
    "template": {
      "title": "Apply for Burial Benefits (VA Form 21P-530EZ)",
      "display_title": "Apply Now",
      "layout": "page-react.html",
      "description": "Use VA Form 21P-530EZ to apply for VA burial benefits online now. Get step-by-step instructions, and consider signing in to save your in-progress application if you need to come back to finish filling it out later.",
      "order": 1,
      "includeBreadcrumbs": true,
      "breadcrumbs_override": [
        {
          "path": "burials-memorials/",
          "name": "Burials and memorials"
        },
        {
          "path": "burials-memorials/veterans-burial-allowance",
          "name": "Veterans burial allowance and transportation benefits"
        },
        {
          "path": "burials-memorials/veterans-burial-allowance/apply-for-allowance-form-21p-530ez",
          "name": "Apply for a Veterans burial allowance and transportation benefits"
        }
      ]
    }
  },
  {
    "appName": "1010ez Health Care Application form",
    "entryName": "hca",
    "rootUrl": "/health-care/apply-for-health-care-form-10-10ez",
    "template": {
      "title": "Apply for VA health care",
      "display_title": "Apply Now",
      "description": "Apply for VA health care benefits. Find out which documents you’ll need, and start your online application today.",
      "body_class": "page-healthcare",
      "layout": "page-react.html",
      "collection": "healthCare",
      "spoke": "Get benefits",
      "order": 4,
      "includeBreadcrumbs": true,
      "breadcrumbs_override": [
        {
          "path": "health-care/",
          "name": "Health care"
        },
        {
          "path": "health-care/apply-for-health-care-form-10-10ez",
          "name": "Apply for VA health care"
        }
      ]
    }
  },
  {
    "appName": "10-10EZR Update health benefits info form",
    "entryName": "ezr",
    "rootUrl": "/my-health/update-benefits-information-form-10-10ezr",
    "template": {
      "title": "Update your VA health benefits information",
      "layout": "page-react.html",
      "vagovprod": true,
      "includeBreadcrumbs": true,
      "private": true,
      "breadcrumbs_override": [
        {
          "name": "VA.gov home",
          "path": ""
        },
        {
          "path": "my-health/",
          "name": "My HealtheVet"
        },
        {
          "path": "my-health/update-benefits-information-form-10-10ezr",
          "name": "Update your VA health benefits information"
        }
      ]
    }
  },
  {
    "appName": "686C-674-v2",
    "entryName": "686C-674-v2",
    "rootUrl": "/manage-dependents/add-remove-form-21-686c-674",
    "template": {
      "layout": "page-react.html",
      "vagovprod": true
    }
  },
  {
    "appName": "21-0538 Dependents verification form",
    "entryName": "0538-dependents-verification",
    "rootUrl": "/manage-dependents/verify-dependents-form-21-0538",
    "productId": "34b9f018-c72d-4788-9cce-b73c8f234116",
    "template": {
      "vagovprod": true,
      "layout": "page-react.html"
    }
  },
  {
    "appName": "21-526EZ disability compensation claim form",
    "entryName": "526EZ-all-claims",
    "rootUrl": "/disability/file-disability-claim-form-21-526ez",
    "template": {
      "title": "File for disability benefits",
      "layout": "page-react.html",
      "description": "Learn how to apply online for disability compensation.",
      "hideFromSidebar": true
    }
  },
  {
    "appName": "Request for Higher-Level Review",
    "entryName": "0996-higher-level-review",
    "rootUrl": "/decision-reviews/higher-level-review/request-higher-level-review-form-20-0996",
    "template": {
      "title": "Request a Higher-Level Review",
      "heading": "Request a Higher-Level Review",
      "display_title": "Request a Higher-Level Review",
      "layout": "page-react.html",
      "description": "Apply online to request a Higher-Level Review.",
      "vagovprod": true
    }
  },
  {
    "appName": "Claims Status",
    "entryName": "claims-status",
    "rootUrl": "/track-claims",
    "template": {
      "title": "Track Claims",
      "layout": "page-react.html",
      "description": "Track the status of your VA claims and appeals."
    },
    "useLocalStylesAndComponents": true
  },
  {
    "appName": "Letters",
    "entryName": "letters",
    "rootUrl": "/records/download-va-letters/letters",
    "template": {
      "title": "Your VA benefit letters and documents",
      "entryname": "letters",
      "layout": "page-react.html",
      "includeBreadcrumbs": true,
      "in_maintenance": false,
      "maintenance_line1": "We’re sorry. The page you’re looking for is currently down while we fix a few things. We’ll get it back online as soon as we can.",
